blank_issues_enabled: false
contact_links:
  - name: Vanjaro Discussions
    url: https://github.com/vanjarosoftware/Vanjaro.Platform/discussions
    about: Get help, solicit feedback and discuss new ideas regarding Vanjaro Platform.
  - name: Tutorial Videos
    url: https://youtube.com/vanjarosoftware
    about: Learn more about Vanjaro Platform.
