name: Move issue to Development Project
on:
  issues:
    types: [milestoned]
jobs:
  Move_Milestoned_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GITHUB_TOKEN }}"
        project-url: "https://github.com/vanjarosoftware/Vanjaro.Platform/projects/7"
        column-name: "In progress"
        milestone-name: "0.5.3|0.5.4|0.5.5"
